<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon />
		<Win32Resource />
		<RootNamespace>Nebula</RootNamespace>
		<AssemblyName>Nebula</AssemblyName>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>4</WarningLevel>
		<DefineConstants>$(DefineConstants);STEAM</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>4</WarningLevel>
		<DefineConstants>STEAM</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\CPUAffinityEditor.exe" />
		<EmbeddedResource Include="Resources\CustomHats\*.png" />
		<EmbeddedResource Include="Resources\*.png" />
		<EmbeddedResource Include="Resources\Help\*.png" />
		<EmbeddedResource Include="Resources\Ghost\*.png" />
		<EmbeddedResource Include="Resources\Locations\*.png" />
		<EmbeddedResource Include="Resources\Languages\*.dat" />
		<EmbeddedResource Include="Resources\Lang.dat" />
		<EmbeddedResource Include="Resources\Color.dat" />
		<EmbeddedResource Include="Resources\RandomName.dat" />
		<EmbeddedResource Include="Resources\Help.dat" />
		<EmbeddedResource Include="Resources\Shaders\*.shader" />
		<EmbeddedResource Include="Resources\Assets\nebula_asset" />
		<EmbeddedResource Include="Resources\Assets\nosrlts_assets" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AmongUs.GameLibs.Steam" Version="2024.6.18" />
		<PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.679" />
	</ItemGroup>

	<Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition="'$(Configuration)' == 'Debug'">
		<Message Text="Second occurrence" />
		<Copy SourceFiles="bin\Debug\net6.0\Nebula.dll" DestinationFolder="C:\Users\26837\Desktop\Among Us-NoS-R-LTS\BepInEx\plugins\" />
	</Target>
	
</Project>