name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Nebula
      run: dotnet build Nebula/NebulaPlugin.csproj --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Nebula-Build
        path: Nebula/bin/Release/net6.0/Nebula.dll
